### ISSUE TITLE
Update to v0.3.2.2

### ISSUE THREAD

**Issue by ProofOfKeags** [Start9Labs/btc-rpc-proxy-wrapper#13] opened 2022-03-02 17:41 UTC
Currently we are pinned to [Start9's Fork](https://github.com/Start9Labs/btc-rpc-proxy/tree/e5d75c71cb2202497e548104996e8fa83b292511) of [btc-rpc-proxy](https://github.com/Kixunil/btc-rpc-proxy). However there has been a release of upstream to v0.3.0.

- [x] Consider bailing on our fork (Resolution, needs async)
- [x] ~~Rebase with upstream if we are sticking with our fork~~
- [x] Make this depend on v22.0 of Bitcoin Core
- [x] Update rpc calls in correspondence with the [new RPC's](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-22.0.md#new-and-updated-rpcs)
- [x] https://github.com/Start9Labs/btc-rpc-proxy-wrapper/issues/15

**Comment by chrisguida** [comment] 2022-03-03 17:15
Doesn't seem like upstream has been updated with new RPCs, what is the last bullet point referring to? We're pinned to [this commit](https://github.com/Start9Labs/btc-rpc-proxy/commits/e5d75c71cb2202497e548104996e8fa83b292511), which includes upstream 0.3.0 (which is the latest upstream version)

**Comment by chrisguida** [comment] 2022-03-03 20:31
Looks like v0.3.1 was a speculative version bump, @dr-bonez was hoping this PR would be accepted https://github.com/Kixunil/btc-rpc-proxy/pull/13

Will rebase that PR and get it merged, hopefully it's mergeable now that it meets the MSRV requirement.

The question still remains what to do about v0.3.2~1 being the wrapper version

**Comment by ProofOfKeags** [comment] 2022-03-08 20:55
> Edit: Oh, I guess you mean new RPCs in bitcoind v22. None of these seem to be new, did I miss any? https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-22.0.md#new-and-updated-rpcs

This is what I meant but didn't copy the link properly.

**Comment by chrisguida** [comment] 2022-03-09 17:13
btc-rpc-proxy does not connect to tor peers. We should probably fix this before updating proxy. Alternatively we can just bump the compatibility with bitcoind 0.22 and call it a day.

cc @dr-bonez

**Comment by ProofOfKeags** [comment] 2022-03-10 00:14
Shouldn't we be able to just fix this by adding the embassy tor proxy to the tcp manager that the block fetcher uses?

**Comment by chrisguida** [comment] 2022-03-10 20:14
Not sure what the issue is exactly. That might be it.

**Comment by chrisguida** [comment] 2022-03-16 17:00
The issue I found above seems to be an issue with peers that have been manually added to bitcoind rather than a problem in general. Confirming now. If so, we need to alter the bip155 PR for proxy to assume port 8333 if none is specified.

**Comment by chrisguida** [comment] 2022-03-16 17:13
Bitcoind issue here https://github.com/Start9Labs/bitcoind-wrapper/issues/53

**Comment by ProofOfKeags** [comment] 2022-03-17 22:15
> We also should probably update bitcoind's config spec to assume port 8333 if none is specified

And also allow the option to specify

**Comment by chrisguida** [comment] 2022-03-18 16:56
Ok specifying port 8333 fixes the above error, but now there's a new error:

`2022-03-18T16:52:21.452925Z Mar 18 16:52:21.452 ERRO Could not fetch block from peers., block_hash: 000000000000000000029d0c1db1e2fac03651f1244f49ae0c2649c85f681104`

**Comment by chrisguida** [comment] 2022-03-21 23:16
Issues with proxy fixed in this PR: https://github.com/Start9Labs/btc-rpc-proxy/pull/9

**Comment by chrisguida** [comment] 2022-03-24 19:24
This PR is now ready to go. It's still based on uptream v0.3.0, but if [this PR](https://github.com/Kixunil/btc-rpc-proxy/pull/13) gets merged upstream will be v0.3.1. Our fork is currently v0.3.1, though we don't have an official release. We already have wrapper version 0.3.2 on 0.2 prod, so we can't backtrack to 0.3.1. So, this version is marked 0.3.2.2, since that's the next version higher than what we already have on prod. We can cut a release on our fork of proxy, or we can continue holding off until the upstream version matches ours.

**Comment by chrisguida** [comment] 2022-03-24 19:26
Closed by https://github.com/Start9Labs/btc-rpc-proxy-wrapper/pull/14

**Closed** 2022-04-15 17:04 UTC
